// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyitPA2ST0PuHciQYmsef0jfpdXky1FrM',
    appId: '1:153755996642:web:21ed8fbdc69112833469bb',
    messagingSenderId: '153755996642',
    projectId: 'kediotoa',
    authDomain: 'kediotoa.firebaseapp.com',
    storageBucket: 'kediotoa.appspot.com',
    measurementId: 'G-M69RSX5WSQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhVYj1XrfohJAwJu-40aYDG-H8GC_BnS0',
    appId: '1:153755996642:android:fec475bace35ba633469bb',
    messagingSenderId: '153755996642',
    projectId: 'kediotoa',
    storageBucket: 'kediotoa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC464t_9-852LN6uziiWMuF7Osm67L0AIM',
    appId: '1:153755996642:ios:fb71d9a7fac2ea853469bb',
    messagingSenderId: '153755996642',
    projectId: 'kediotoa',
    storageBucket: 'kediotoa.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC464t_9-852LN6uziiWMuF7Osm67L0AIM',
    appId: '1:153755996642:ios:fb71d9a7fac2ea853469bb',
    messagingSenderId: '153755996642',
    projectId: 'kediotoa',
    storageBucket: 'kediotoa.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyitPA2ST0PuHciQYmsef0jfpdXky1FrM',
    appId: '1:153755996642:web:402bc17a01905da33469bb',
    messagingSenderId: '153755996642',
    projectId: 'kediotoa',
    authDomain: 'kediotoa.firebaseapp.com',
    storageBucket: 'kediotoa.appspot.com',
    measurementId: 'G-2LNJL79RH9',
  );
}
